### ISSUE TITLE
Possible issue with building for 64 bit concerning audio/midi.

### ISSUE THREAD

**Issue by mikobuntu** [DISTRHO/ZynAddSubFX#1]
Hi @falkTX  I was able to build and successfully run your branch of ZynAddsubFX as a native linux vst, under your instruction on my ubuntu 12.04 32 bit machine and so far so good with testing in Renoise, ....
... But I am having serious as in "no audio" running a successful build on my 64 bit machine. Both Renoise and Bitwig load ZASF ok, but on both I can see I am sending midi ok to the plugin, but getting no audio.
is there any way to debug this easily?   One thing i do notice on my 64 bit machine is that I have access to the top menu settings directly in ZASF, which i think I did'nt get in 32bit, but the gui looks exactly the same i.e a few slight changes like no green knobs compared to the normal NTK build, maybe I'm missing something simple... 

* edit i do actually have access to the menus on my 32 bit build *

thanks Mikobuntu

**Comment by falkTX** [comment]
I only use 64bit systems and never experienced this issue.
Does the same happen with the zyn included in carla for you?

**Comment by mikobuntu** [comment]
@falkTX   Yes this is strange behaviour indeed. No Zyn included with Carla runs perfectly for me in Renoise, Bitwig and LMMS. I'm wondering is the NIO settings maybe hard-coded ( I can access the menu, but see no options ). Also note my system wide Zyn 2.4.4 that I compiled with NTK support also works as expected for me, as I remember this ZynAdd vst is compiled somehow against it.

**Comment by mikobuntu** [comment]
@falkTX      ....

This output to compare which shared objects are loaded at runtime using the vst binary.

Below is the out put of ' ldd ZynAddSubFX-vst.so '  from the terminal of both the 32bit( successful)  and 64bit ( no audio/midi?) builds.

I see a difference in loaded libs, but maybe this is just platform specific:?

32 bit ldd output:-

mikobuntu@mikobuntu-Aspire-5332:~/Desktop/zyn-falk/ZynAddSubFX/bin$ ldd ZynAddSubFX-vst.so 
	linux-gate.so.1 =>  (0xb7732000)
	libfftw3.so.3 => /usr/lib/libfftw3.so.3 (0xb74c3000)
	libmxml.so.1 => /usr/lib/libmxml.so.1 (0xb74ba000)
	libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xb749e000)
	libz.so.1 => /lib/i386-linux-gnu/libz.so.1 (0xb7488000)
	libntk_images.so.1 => /usr/lib/i386-linux-gnu/libntk_images.so.1 (0xb747a000)
	libntk.so.1 => /usr/lib/i386-linux-gnu/libntk.so.1 (0xb7356000)
	libX11.so.6 => /usr/lib/i386-linux-gnu/libX11.so.6 (0xb7222000)
	libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0xb712d000)
	libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xb7101000)
	libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xb70e3000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xb6f38000)
	/lib/ld-linux.so.2 (0xb7733000)
	libpng12.so.0 => /lib/i386-linux-gnu/libpng12.so.0 (0xb6f0e000)
	libfontconfig.so.1 => /usr/lib/i386-linux-gnu/libfontconfig.so.1 (0xb6ed9000)
	libXft.so.2 => /usr/lib/i386-linux-gnu/libXft.so.2 (0xb6ec3000)
	libcairo.so.2 => /usr/lib/i386-linux-gnu/libcairo.so.2 (0xb6df8000)
	libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xb6df3000)
	libxcb.so.1 => /usr/lib/i386-linux-gnu/libxcb.so.1 (0xb6dd2000)
	libfreetype.so.6 => /usr/lib/i386-linux-gnu/libfreetype.so.6 (0xb6d37000)
	libexpat.so.1 => /lib/i386-linux-gnu/libexpat.so.1 (0xb6d0d000)
	libXrender.so.1 => /usr/lib/i386-linux-gnu/libXrender.so.1 (0xb6d03000)
	libpixman-1.so.0 => /usr/lib/i386-linux-gnu/libpixman-1.so.0 (0xb6c68000)
	libxcb-shm.so.0 => /usr/lib/i386-linux-gnu/libxcb-shm.so.0 (0xb6c64000)
	libxcb-render.so.0 => /usr/lib/i386-linux-gnu/libxcb-render.so.0 (0xb6c59000)
	libXau.so.6 => /usr/lib/i386-linux-gnu/libXau.so.6 (0xb6c55000)
	libXdmcp.so.6 => /usr/lib/i386-linux-gnu/libXdmcp.so.6 (0xb6c4e000)



64bit ldd output:-

mikobuntu@mikobuntu-MS-7721:~/ZynAddSubFX-VST/bin$ ldd ZynAddSubFX-vst.so 
	linux-vdso.so.1 =>  (0x00007fff58bd0000)
	libfftw3.so.3 => /usr/lib/x86_64-linux-gnu/libfftw3.so.3 (0x00007f8120ee0000)
	libmxml.so.1 => /usr/lib/libmxml.so.1 (0x00007f8120cd0000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8120ab0000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f8120890000)
	libntk_images.so.1 => /usr/local/lib/libntk_images.so.1 (0x00007f8120680000)
	libntk.so.1 => /usr/local/lib/libntk.so.1 (0x00007f8120348000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f8120010000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f811fd08000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f811fa00000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f811f7e8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f811f420000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f81215f0000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f811f1f8000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f811efb8000)
	libXft.so.2 => /usr/lib/x86_64-linux-gnu/libXft.so.2 (0x00007f811eda0000)
	libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f811ea90000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f811e888000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f811e668000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f811e3c0000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f811e190000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f811df80000)
	libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f811dcd0000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f811dac8000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f811d8b8000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f811d6a0000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f811d498000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f811d290000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f811d088000)


I'm unsure of any other way to debug this ..thanks :)

**Comment by mikobuntu** [comment]
@falkTX   below is the output ( ubuntu pastebin link )  of 'make' , maybe this will help somewhat?  It could be some misconfiguration on my machine, note I have now installed ZynAdd version: 2.5.0~git20150225-1kxstudio1 on my system, but this still makes no difference to the original bug ... anyway thanks for your time and looking into this, hopefully I am not wasting your time here:-

http://paste.ubuntu.com/10445931/

**Comment by mikobuntu** [comment]
@falkTX  hi ;)

**Update**

ZynAddSubFX-vst.so will work " ironically" when I run it using your Carla/LMMS Plugin. This at 1st lead me to believe that jack was the problem because i was running LMMS with the alsa backend, but i soon ruled that out as when testing with Renoise and Bitwig with alsa and still I have no audio/midi within them.

Another observation was when running Carla standalone through jack I still have no audio/midi and the terminal shows multiple output of :- " darn it: 44100 vs 48000 "  ... could this be somehow related?

thanks Mikobuntu :)

**Comment by mikobuntu** [comment]
@falkTX  **solved**  wow, how did I not figure this out before, ZynAddSubFX-vst.so is hard-coded to 44100Hz, I was running jack at 48000Hz. So I will close this out as solved, but make a feature request for   ability to choose an alternative samplerate in the vst.

anyway sorry If I wasted your time, although it was a learning curve for me :) thanks
